# Generated by Django 3.2.3 on 2021-05-24 21:58

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('names', models.CharField(max_length=50)),
                ('surnames', models.CharField(max_length=50)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('career_path', models.TextField(blank=True)),
                ('political_party', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='null', upload_to='media/candidate-photos')),
                ('photo_political_party', models.ImageField(default='null', upload_to='media/political-party')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
